
server:
  port: 9099

spring:
  application:
    name: gateway-alpha
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        health-check-interval: 30s
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: alpha-service
          uri: lb://service-alpha
          predicates:
            - Path=/alpha/**
          filters:
            - StripPrefix=1
        - id: beta-service
          uri: lb://service-beta
          predicates:
            - Path=/beta/**
          filters:
            - StripPrefix=1
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway