server:
  port: 8084

spring:
  application:
    name: service-beta
  cloud:
    consul:
#      host: 192.168.50.116
      discovery:
        health-check-interval: 3s
        prefer-ip-address: true
        enabled: true
        health-check-path: /health
  zipkin:
    base-url: http://127.0.0.1:9411
#    base-url: http://192.168.50.116:9411